// <auto-generated />
using System;
using CofiApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CofiApp.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CofiApp.Domain.Authentication.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "All"
                        },
                        new
                        {
                            Id = 2,
                            Name = "GetUsers"
                        },
                        new
                        {
                            Id = 3,
                            Name = "GetUserById"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CreateUser"
                        },
                        new
                        {
                            Id = 5,
                            Name = "UpdateUser"
                        },
                        new
                        {
                            Id = 6,
                            Name = "RemoveUser"
                        },
                        new
                        {
                            Id = 7,
                            Name = "GetRoles"
                        },
                        new
                        {
                            Id = 8,
                            Name = "CreateRole"
                        },
                        new
                        {
                            Id = 9,
                            Name = "UpdateRole"
                        },
                        new
                        {
                            Id = 10,
                            Name = "RemoveRole"
                        },
                        new
                        {
                            Id = 11,
                            Name = "GetRolesPermissions"
                        },
                        new
                        {
                            Id = 12,
                            Name = "AssignPermission"
                        },
                        new
                        {
                            Id = 13,
                            Name = "AssignUser"
                        },
                        new
                        {
                            Id = 14,
                            Name = "GetMenuCategories"
                        },
                        new
                        {
                            Id = 15,
                            Name = "GetMenuCategoryById"
                        },
                        new
                        {
                            Id = 16,
                            Name = "CreateMenuCategory"
                        },
                        new
                        {
                            Id = 17,
                            Name = "UpdateMenuCategory"
                        },
                        new
                        {
                            Id = 18,
                            Name = "RemoveMenuCategory"
                        },
                        new
                        {
                            Id = 19,
                            Name = "UpdateMenuCategoriesDisplayOrder"
                        },
                        new
                        {
                            Id = 20,
                            Name = "GetProducts"
                        },
                        new
                        {
                            Id = 21,
                            Name = "GetProductById"
                        },
                        new
                        {
                            Id = 22,
                            Name = "CreateProduct"
                        },
                        new
                        {
                            Id = 23,
                            Name = "UpdateProduct"
                        },
                        new
                        {
                            Id = 24,
                            Name = "RemoveProduct"
                        },
                        new
                        {
                            Id = 25,
                            Name = "UpdateProductMenuCategories"
                        },
                        new
                        {
                            Id = 26,
                            Name = "GetProductOptionGroupsWithOptions"
                        },
                        new
                        {
                            Id = 27,
                            Name = "CreateProductOptionGroup"
                        },
                        new
                        {
                            Id = 28,
                            Name = "UpdateProductOptionGroup"
                        },
                        new
                        {
                            Id = 29,
                            Name = "RemoveProductOptionGroup"
                        },
                        new
                        {
                            Id = 30,
                            Name = "CreateProductOption"
                        },
                        new
                        {
                            Id = 31,
                            Name = "UpdateProductOption"
                        },
                        new
                        {
                            Id = 32,
                            Name = "RemoveProductOption"
                        },
                        new
                        {
                            Id = 33,
                            Name = "GetActiveBasket"
                        },
                        new
                        {
                            Id = 34,
                            Name = "CreateBasketItem"
                        },
                        new
                        {
                            Id = 35,
                            Name = "UpdateBasketItem"
                        },
                        new
                        {
                            Id = 36,
                            Name = "UpdateBasketItemQuantity"
                        },
                        new
                        {
                            Id = 37,
                            Name = "ClearBasket"
                        },
                        new
                        {
                            Id = 38,
                            Name = "GetShopOrders"
                        },
                        new
                        {
                            Id = 39,
                            Name = "GetShopOrderById"
                        },
                        new
                        {
                            Id = 40,
                            Name = "CancelShopOrder"
                        },
                        new
                        {
                            Id = 41,
                            Name = "ProcessShopOrder"
                        },
                        new
                        {
                            Id = 42,
                            Name = "CompleteShopOrder"
                        },
                        new
                        {
                            Id = 43,
                            Name = "GetCustomerOrders"
                        },
                        new
                        {
                            Id = 44,
                            Name = "GetCustomerOrderById"
                        },
                        new
                        {
                            Id = 45,
                            Name = "CreateCustomerOrder"
                        },
                        new
                        {
                            Id = 46,
                            Name = "CancelCustomerOrder"
                        },
                        new
                        {
                            Id = 47,
                            Name = "UploadProductImageFile"
                        },
                        new
                        {
                            Id = 48,
                            Name = "RemoveProductImageFile"
                        });
                });

            modelBuilder.Entity("CofiApp.Domain.Authentication.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("38d625fb-6965-41da-a302-2a595829231c"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 761, DateTimeKind.Utc).AddTicks(6894),
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("CofiApp.Domain.Authentication.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("38d625fb-6965-41da-a302-2a595829231c"),
                            PermissionId = 1
                        });
                });

            modelBuilder.Entity("CofiApp.Domain.Authentication.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("f8c0b3e4-febe-450b-baff-bea13fcdd59c"),
                            RoleId = new Guid("38d625fb-6965-41da-a302-2a595829231c")
                        });
                });

            modelBuilder.Entity("CofiApp.Domain.BasketItemOptionGroups.BasketItemOptionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasketItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductOptionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BasketItemId");

                    b.HasIndex("ProductOptionGroupId");

                    b.ToTable("BasketItemOptionGroups", (string)null);
                });

            modelBuilder.Entity("CofiApp.Domain.BasketItemOptions.BasketItemOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasketItemOptionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BasketItemOptionGroupId");

                    b.HasIndex("ProductOptionId");

                    b.ToTable("BasketItemOptions", (string)null);
                });

            modelBuilder.Entity("CofiApp.Domain.BasketItems.BasketItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketItems", (string)null);
                });

            modelBuilder.Entity("CofiApp.Domain.Baskets.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Baskets", (string)null);
                });

            modelBuilder.Entity("CofiApp.Domain.Files.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Files", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CofiApp.Domain.MenuCategories.MenuCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MenuCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b878e4c2-87e0-4108-b550-5185359428b3"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3836),
                            DisplayOrder = 1,
                            Name = "Öne Çıkaranlar"
                        },
                        new
                        {
                            Id = new Guid("9035a449-e905-4e67-88cc-244521986ee1"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3838),
                            DisplayOrder = 2,
                            Name = "Sıcak Kahveler"
                        },
                        new
                        {
                            Id = new Guid("930afb5b-cb65-4ad7-b54a-4e94900bf3df"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3846),
                            DisplayOrder = 3,
                            Name = "Soğuk Kahveler"
                        });
                });

            modelBuilder.Entity("CofiApp.Domain.OrderItemOptionGroups.OrderItemOptionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ProductOptionGroupAllowMultiple")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductOptionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ProductOptionGroupIsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ProductOptionGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.ToTable("OrderItemOptionGroups", (string)null);
                });

            modelBuilder.Entity("CofiApp.Domain.OrderItemOptions.OrderItemOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderItemOptionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductOptionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ProductOptionPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemOptionGroupId");

                    b.ToTable("OrderItemOptions", (string)null);
                });

            modelBuilder.Entity("CofiApp.Domain.OrderItems.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("CofiApp.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("CofiApp.Domain.ProductMenuCategories.ProductMenuCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "MenuCategoryId");

                    b.HasIndex("MenuCategoryId");

                    b.ToTable("ProductMenuCategories", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("f1545f8d-739c-4902-848b-efff5fc01cc2"),
                            MenuCategoryId = new Guid("b878e4c2-87e0-4108-b550-5185359428b3")
                        },
                        new
                        {
                            ProductId = new Guid("f1545f8d-739c-4902-848b-efff5fc01cc2"),
                            MenuCategoryId = new Guid("9035a449-e905-4e67-88cc-244521986ee1")
                        },
                        new
                        {
                            ProductId = new Guid("77c54e6c-509d-45be-9c68-a538159bd417"),
                            MenuCategoryId = new Guid("b878e4c2-87e0-4108-b550-5185359428b3")
                        },
                        new
                        {
                            ProductId = new Guid("77c54e6c-509d-45be-9c68-a538159bd417"),
                            MenuCategoryId = new Guid("9035a449-e905-4e67-88cc-244521986ee1")
                        },
                        new
                        {
                            ProductId = new Guid("c1b1caa3-1153-414e-83a2-ccec45491202"),
                            MenuCategoryId = new Guid("930afb5b-cb65-4ad7-b54a-4e94900bf3df")
                        },
                        new
                        {
                            ProductId = new Guid("98822077-d47d-49aa-bd83-a16d87a29437"),
                            MenuCategoryId = new Guid("930afb5b-cb65-4ad7-b54a-4e94900bf3df")
                        });
                });

            modelBuilder.Entity("CofiApp.Domain.ProductOptionGroups.ProductOptionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowMultiple")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOptionGroups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77a83bdf-2773-4af3-aa6b-1700b3f187fb"),
                            AllowMultiple = false,
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3923),
                            IsRequired = true,
                            Name = "Boy Seçimi",
                            ProductId = new Guid("f1545f8d-739c-4902-848b-efff5fc01cc2")
                        },
                        new
                        {
                            Id = new Guid("5131273b-981f-4c7c-9b12-ad4f06c15a20"),
                            AllowMultiple = false,
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3924),
                            IsRequired = true,
                            Name = "Boy Seçimi",
                            ProductId = new Guid("77c54e6c-509d-45be-9c68-a538159bd417")
                        },
                        new
                        {
                            Id = new Guid("32b68ebe-5c25-43d2-99a5-5b5109497a78"),
                            AllowMultiple = false,
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3925),
                            IsRequired = true,
                            Name = "Boy Seçimi",
                            ProductId = new Guid("98822077-d47d-49aa-bd83-a16d87a29437")
                        },
                        new
                        {
                            Id = new Guid("9ab6d76e-6218-42ff-97d7-eac060bc052a"),
                            AllowMultiple = false,
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3931),
                            IsRequired = true,
                            Name = "Boy Seçimi",
                            ProductId = new Guid("c1b1caa3-1153-414e-83a2-ccec45491202")
                        });
                });

            modelBuilder.Entity("CofiApp.Domain.ProductOptions.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductOptionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductOptionGroupId");

                    b.ToTable("ProductOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3024dbd8-873d-485c-ae41-66ef74eacbde"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3957),
                            Name = "Standart",
                            Price = 0m,
                            ProductOptionGroupId = new Guid("77a83bdf-2773-4af3-aa6b-1700b3f187fb")
                        },
                        new
                        {
                            Id = new Guid("7a42c8ec-cf79-426c-987b-ad4e7abbccb3"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3959),
                            Name = "Orta",
                            Price = 2m,
                            ProductOptionGroupId = new Guid("77a83bdf-2773-4af3-aa6b-1700b3f187fb")
                        },
                        new
                        {
                            Id = new Guid("1d010e38-039d-4b87-b184-2bf2b4782e4d"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3960),
                            Name = "Büyük",
                            Price = 4m,
                            ProductOptionGroupId = new Guid("77a83bdf-2773-4af3-aa6b-1700b3f187fb")
                        },
                        new
                        {
                            Id = new Guid("660481c8-4895-49fb-a450-a1d38b22cbb5"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3961),
                            Name = "Standart",
                            Price = 0m,
                            ProductOptionGroupId = new Guid("5131273b-981f-4c7c-9b12-ad4f06c15a20")
                        },
                        new
                        {
                            Id = new Guid("a156020b-320e-4571-8d23-5ea284ed8bcf"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3962),
                            Name = "Orta",
                            Price = 2m,
                            ProductOptionGroupId = new Guid("5131273b-981f-4c7c-9b12-ad4f06c15a20")
                        },
                        new
                        {
                            Id = new Guid("df35ba80-01f6-4476-8f60-ed2dc2bd913a"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3963),
                            Name = "Büyük",
                            Price = 4m,
                            ProductOptionGroupId = new Guid("5131273b-981f-4c7c-9b12-ad4f06c15a20")
                        },
                        new
                        {
                            Id = new Guid("cb3a83a7-b5c3-4957-b1c1-1fd87a389768"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3964),
                            Name = "Standart",
                            Price = 0m,
                            ProductOptionGroupId = new Guid("32b68ebe-5c25-43d2-99a5-5b5109497a78")
                        },
                        new
                        {
                            Id = new Guid("4acd8f6f-ed49-40f7-bb99-61da60218586"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3967),
                            Name = "Orta",
                            Price = 2m,
                            ProductOptionGroupId = new Guid("32b68ebe-5c25-43d2-99a5-5b5109497a78")
                        },
                        new
                        {
                            Id = new Guid("a63c9a21-0787-4a62-9820-99e39c0802e7"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3968),
                            Name = "Büyük",
                            Price = 4m,
                            ProductOptionGroupId = new Guid("32b68ebe-5c25-43d2-99a5-5b5109497a78")
                        },
                        new
                        {
                            Id = new Guid("288c8d06-c729-47a5-b9ab-48a3cfd1548c"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3970),
                            Name = "Standart",
                            Price = 0m,
                            ProductOptionGroupId = new Guid("9ab6d76e-6218-42ff-97d7-eac060bc052a")
                        },
                        new
                        {
                            Id = new Guid("b63a2a09-745b-499d-946b-2a0f824d74d9"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3971),
                            Name = "Orta",
                            Price = 2m,
                            ProductOptionGroupId = new Guid("9ab6d76e-6218-42ff-97d7-eac060bc052a")
                        },
                        new
                        {
                            Id = new Guid("9584d23b-9f0b-4572-8bff-726bfa61bb2a"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3972),
                            Name = "Büyük",
                            Price = 4m,
                            ProductOptionGroupId = new Guid("9ab6d76e-6218-42ff-97d7-eac060bc052a")
                        });
                });

            modelBuilder.Entity("CofiApp.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProductImageFileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductImageFileId")
                        .IsUnique()
                        .HasFilter("[ProductImageFileId] IS NOT NULL");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1545f8d-739c-4902-848b-efff5fc01cc2"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3877),
                            Deleted = false,
                            Name = "Latte",
                            Price = 15m
                        },
                        new
                        {
                            Id = new Guid("77c54e6c-509d-45be-9c68-a538159bd417"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3879),
                            Deleted = false,
                            Name = "Mocha",
                            Price = 20m
                        },
                        new
                        {
                            Id = new Guid("c1b1caa3-1153-414e-83a2-ccec45491202"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3897),
                            Deleted = false,
                            Name = "Ice Americano",
                            Price = 10m
                        },
                        new
                        {
                            Id = new Guid("98822077-d47d-49aa-bd83-a16d87a29437"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3898),
                            Deleted = false,
                            Name = "Ice Latte",
                            Price = 10m
                        });
                });

            modelBuilder.Entity("CofiApp.Domain.UserRefreshTokens.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserRefreshTokens", (string)null);
                });

            modelBuilder.Entity("CofiApp.Domain.UserVerificationTokens.UserVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserVerificationTokens", (string)null);
                });

            modelBuilder.Entity("CofiApp.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f8c0b3e4-febe-450b-baff-bea13fcdd59c"),
                            CreatedOnUtc = new DateTime(2024, 9, 19, 14, 4, 56, 765, DateTimeKind.Utc).AddTicks(3699),
                            Deleted = false,
                            Email = "eneskrdnz28@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Enes",
                            LastName = "Karadeniz",
                            PasswordHash = "5CC26F643A36666DA687F8C28BAEBE9FEBAD3A37353B99500CE00B798D51D639-5E77AD3E3CBA5BDAFC6B592CE6A8D871",
                            PhoneNumberConfirmed = false
                        });
                });

            modelBuilder.Entity("CofiApp.Domain.ProductImageFiles.ProductImageFile", b =>
                {
                    b.HasBaseType("CofiApp.Domain.Files.File");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("ProductImageFiles", (string)null);
                });

            modelBuilder.Entity("CofiApp.Domain.Authentication.RolePermission", b =>
                {
                    b.HasOne("CofiApp.Domain.Authentication.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CofiApp.Domain.Authentication.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CofiApp.Domain.Authentication.UserRole", b =>
                {
                    b.HasOne("CofiApp.Domain.Authentication.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CofiApp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CofiApp.Domain.BasketItemOptionGroups.BasketItemOptionGroup", b =>
                {
                    b.HasOne("CofiApp.Domain.BasketItems.BasketItem", "BasketItem")
                        .WithMany("BasketItemOptionGroups")
                        .HasForeignKey("BasketItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CofiApp.Domain.ProductOptionGroups.ProductOptionGroup", "ProductOptionGroup")
                        .WithMany("BasketItemOptionGroups")
                        .HasForeignKey("ProductOptionGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BasketItem");

                    b.Navigation("ProductOptionGroup");
                });

            modelBuilder.Entity("CofiApp.Domain.BasketItemOptions.BasketItemOption", b =>
                {
                    b.HasOne("CofiApp.Domain.BasketItemOptionGroups.BasketItemOptionGroup", "BasketItemOptionGroup")
                        .WithMany("BasketItemOptions")
                        .HasForeignKey("BasketItemOptionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CofiApp.Domain.ProductOptions.ProductOption", "ProductOption")
                        .WithMany("BasketItemOptions")
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BasketItemOptionGroup");

                    b.Navigation("ProductOption");
                });

            modelBuilder.Entity("CofiApp.Domain.BasketItems.BasketItem", b =>
                {
                    b.HasOne("CofiApp.Domain.Baskets.Basket", "Basket")
                        .WithMany("BasketItems")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CofiApp.Domain.Products.Product", "Product")
                        .WithMany("BasketItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CofiApp.Domain.Baskets.Basket", b =>
                {
                    b.HasOne("CofiApp.Domain.Users.User", "User")
                        .WithMany("Baskets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CofiApp.Domain.OrderItemOptionGroups.OrderItemOptionGroup", b =>
                {
                    b.HasOne("CofiApp.Domain.OrderItems.OrderItem", "OrderItem")
                        .WithMany("OrderItemOptionGroups")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("CofiApp.Domain.OrderItemOptions.OrderItemOption", b =>
                {
                    b.HasOne("CofiApp.Domain.OrderItemOptionGroups.OrderItemOptionGroup", "OrderItemOptionGroup")
                        .WithMany("OrderItemOptions")
                        .HasForeignKey("OrderItemOptionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItemOptionGroup");
                });

            modelBuilder.Entity("CofiApp.Domain.OrderItems.OrderItem", b =>
                {
                    b.HasOne("CofiApp.Domain.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CofiApp.Domain.Orders.Order", b =>
                {
                    b.HasOne("CofiApp.Domain.Baskets.Basket", "Basket")
                        .WithMany("Orders")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CofiApp.Domain.Users.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CofiApp.Domain.ProductMenuCategories.ProductMenuCategory", b =>
                {
                    b.HasOne("CofiApp.Domain.MenuCategories.MenuCategory", "MenuCategory")
                        .WithMany("ProductMenuCategories")
                        .HasForeignKey("MenuCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CofiApp.Domain.Products.Product", "Product")
                        .WithMany("ProductMenuCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuCategory");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CofiApp.Domain.ProductOptionGroups.ProductOptionGroup", b =>
                {
                    b.HasOne("CofiApp.Domain.Products.Product", "Product")
                        .WithMany("ProductOptionGroups")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CofiApp.Domain.ProductOptions.ProductOption", b =>
                {
                    b.HasOne("CofiApp.Domain.ProductOptionGroups.ProductOptionGroup", "ProductOptionGroup")
                        .WithMany("ProductOptions")
                        .HasForeignKey("ProductOptionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductOptionGroup");
                });

            modelBuilder.Entity("CofiApp.Domain.Products.Product", b =>
                {
                    b.HasOne("CofiApp.Domain.ProductImageFiles.ProductImageFile", "ProductImageFile")
                        .WithOne("Product")
                        .HasForeignKey("CofiApp.Domain.Products.Product", "ProductImageFileId");

                    b.Navigation("ProductImageFile");
                });

            modelBuilder.Entity("CofiApp.Domain.UserRefreshTokens.UserRefreshToken", b =>
                {
                    b.HasOne("CofiApp.Domain.Users.User", "User")
                        .WithOne("UserRefreshToken")
                        .HasForeignKey("CofiApp.Domain.UserRefreshTokens.UserRefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CofiApp.Domain.UserVerificationTokens.UserVerificationToken", b =>
                {
                    b.HasOne("CofiApp.Domain.Users.User", "User")
                        .WithOne("UserVerificationToken")
                        .HasForeignKey("CofiApp.Domain.UserVerificationTokens.UserVerificationToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CofiApp.Domain.ProductImageFiles.ProductImageFile", b =>
                {
                    b.HasOne("CofiApp.Domain.Files.File", null)
                        .WithOne()
                        .HasForeignKey("CofiApp.Domain.ProductImageFiles.ProductImageFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CofiApp.Domain.BasketItemOptionGroups.BasketItemOptionGroup", b =>
                {
                    b.Navigation("BasketItemOptions");
                });

            modelBuilder.Entity("CofiApp.Domain.BasketItems.BasketItem", b =>
                {
                    b.Navigation("BasketItemOptionGroups");
                });

            modelBuilder.Entity("CofiApp.Domain.Baskets.Basket", b =>
                {
                    b.Navigation("BasketItems");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CofiApp.Domain.MenuCategories.MenuCategory", b =>
                {
                    b.Navigation("ProductMenuCategories");
                });

            modelBuilder.Entity("CofiApp.Domain.OrderItemOptionGroups.OrderItemOptionGroup", b =>
                {
                    b.Navigation("OrderItemOptions");
                });

            modelBuilder.Entity("CofiApp.Domain.OrderItems.OrderItem", b =>
                {
                    b.Navigation("OrderItemOptionGroups");
                });

            modelBuilder.Entity("CofiApp.Domain.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CofiApp.Domain.ProductOptionGroups.ProductOptionGroup", b =>
                {
                    b.Navigation("BasketItemOptionGroups");

                    b.Navigation("ProductOptions");
                });

            modelBuilder.Entity("CofiApp.Domain.ProductOptions.ProductOption", b =>
                {
                    b.Navigation("BasketItemOptions");
                });

            modelBuilder.Entity("CofiApp.Domain.Products.Product", b =>
                {
                    b.Navigation("BasketItems");

                    b.Navigation("ProductMenuCategories");

                    b.Navigation("ProductOptionGroups");
                });

            modelBuilder.Entity("CofiApp.Domain.Users.User", b =>
                {
                    b.Navigation("Baskets");

                    b.Navigation("Orders");

                    b.Navigation("UserRefreshToken")
                        .IsRequired();

                    b.Navigation("UserVerificationToken")
                        .IsRequired();
                });

            modelBuilder.Entity("CofiApp.Domain.ProductImageFiles.ProductImageFile", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
